### ISSUE TITLE
Checklist for submission

### ISSUE THREAD

**Issue by Droffilc13** [AY2122S1-CS2103T-T13-2/tp#291]
# Production Status

### *Deadline: 8 Nov 2021, Mon*

# Submitted!
**Drag submitted documents into this area**
- [x] Click the item and just drag it to this task list 😄 
- [x] Developer Guide
- [x] User Guide
- [x] ta2.jar
- [x] Guo Rui (PPP)
- [x] Clifford (PPP)
- [x] Yiheng (PPP)
- [x] Demo Video
- [x] Wei Chang (PPP)
- [x] Tao Jun (PPP)

**Comment by Droffilc13** [comment]
**ALL SUBMITTED** on 8 Nov 2021, 8.38AM!
